# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoorBell' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Koloda', '~> 4.0'
  pod 'FSCalendar'
  pod 'SwiftyJSON'
  pod 'MBProgressHUD', '~> 1.0.0'
  # Pods for DoorBell

end
